default_platform(:ios)

platform :ios do

  desc "Run unit tests"
  lane :test do
    scan(
      workspace: "Mercury Jacket.xcworkspace",
      scheme: "Mercury Jacket",
      devices: ["iPhone 15"],
      clean: true,
      code_coverage: true
    )
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      raise_if_swiftlint_error: true,
      strict: false
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      workspace: "Mercury Jacket.xcworkspace",
      scheme: "Mercury Jacket",
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
