platform :ios, '16.2'
inhibit_all_warnings!

target 'Mercury Jacket' do
  # Static linkage avoids broken per-framework rsync embed paths with older CocoaPods/Xcode combos.
  use_frameworks! :linkage => :static

  pod 'Firebase/Core', '~> 10.0'
  pod 'SwiftyGif', '~> 5.4'
  pod 'DottedLineView', '~> 1.0'
  pod 'IQKeyboardManager'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.2'
    end
  end
end
