platform :ios, '15.0'
inhibit_all_warnings!

target 'Mercury Jacket' do
  use_frameworks!

  pod 'Firebase/Core', '~> 10.0'
  pod 'SwiftyGif', '~> 5.4'
  pod 'DottedLineView', '~> 2.0'
  pod 'IQKeyboardManager'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
